#! /bin/bash
# Gerenciador criado por Marcelo Rocha | m.rocha@outlook.com.br

while true; do
    # Exibe o menu principal
    echo "Escolha uma opção:"
    echo "1 - Atualizar pacotes"
    echo "2 - Pesquisar pacotes"
    echo "3 - Instalar pacotes"
    echo "4 - Remover pacotes"
    echo "5 - Limpar pacotes"
    echo "6 - Sair"
    read -p "Opção: " choice

    case $choice in
        1)
            # Atualiza os pacotes
            sudo xbps-install -Suvy
            update-grub
            echo "Pacotes atualizados com sucesso!"
            ;;
        2)
            # Permite pesquisar pacotes
            read -p "Digite o nome do pacote: " search
            if [ -n "$search" ]; then
                output=$(sudo xbps-query -Rs "$search")
                if [ -n "$output" ]; then
                    echo "$output"
                else
                    echo "Nenhum pacote encontrado."
                fi
            fi
            ;;
        3)
            # Permite instalar pacotes
            read -p "Digite o nome do pacote a ser instalado: " install
            if [ -n "$install" ]; then
                sudo xbps-install -y "$install"
                echo "Pacote $install instalado com sucesso!"
            fi
            ;;
        4)
            # Permite remover pacotes
            read -p "Digite o nome do pacote a ser removido: " remove
            if [ -n "$remove" ]; then
                sudo xbps-remove -y "$remove"
                echo "Pacote $remove removido com sucesso!"
            fi
            ;;
        5)
            # Permite limpar pacotes
            sudo xbps-remove -Ooy
            echo "Pacotes limpos com sucesso!"
            ;;
        6)
            # Sai do script
            break
            ;;
        *)
            echo "Opção inválida."
            ;;
    esac
done
